{"uri":"file:///home/tarcisio/dev/phpfin/vendor/symfony/translation/Exception/RuntimeException.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Symfony\\Component\\Translation\\Exception","location":[11,0,11,50]},{"kind":1,"name":"Symfony\\Component\\Translation\\Exception\\RuntimeException","location":[18,0,20,1],"associated":[{"kind":1,"name":"RuntimeException"},{"kind":2,"name":"Symfony\\Component\\Translation\\Exception\\ExceptionInterface"}],"description":"Base RuntimeException for the Translation component."}]}}