{"uri":"file:///home/tarcisio/dev/phpfin/vendor/twig/twig/lib/Twig/Error.php","root":{"kind":0,"name":"","children":[{"kind":1,"name":"Twig_Error","location":[33,0,364,1],"associated":[{"kind":1,"name":"Exception"}],"description":"Twig base exception.\n\nThis exception class and its children must only be used when\nan error occurs during the loading of a template, when a syntax error\nis detected in a template, or when rendering a template. Other\nerrors must use regular PHP exception classes (like when the template\ncache directory is not writable for instance).\n\nTo help debugging template issues, this class tracks the original template\nname and line where the error occurred.\n\nWhenever possible, you must set these information (original template name\nand line number) yourself by passing them to the constructor. If some or all\nthese information are not available from where you throw the exception, then\nthis class will guess them automatically (when the line number is set to -1\nand/or the name is set to null). As this is a costly operation, this\ncan be disabled by passing false for both the name and the line number\nwhen creating a new instance of this class.","children":[{"kind":16,"name":"$lineno","modifiers":2,"location":[35,14,35,21],"scope":"Twig_Error"},{"kind":16,"name":"$filename","modifiers":2,"location":[37,14,37,23],"scope":"Twig_Error"},{"kind":16,"name":"$rawMessage","modifiers":2,"location":[38,14,38,25],"scope":"Twig_Error"},{"kind":16,"name":"$previous","modifiers":2,"location":[39,14,39,23],"scope":"Twig_Error"},{"kind":16,"name":"$sourcePath","modifiers":4,"location":[41,12,41,23],"scope":"Twig_Error"},{"kind":16,"name":"$sourceCode","modifiers":4,"location":[42,12,42,23],"scope":"Twig_Error"},{"kind":32,"name":"__construct","modifiers":1,"location":[61,4,90,5],"description":"Constructor.\n\nSet both the line number and the name to false to\ndisable automatic guessing of the original template name\nand line number.\n\nSet the line number to -1 to enable its automatic guessing.\nSet the name to null to enable its automatic guessing.\n\nBy default, automatic guessing is enabled.","scope":"Twig_Error","children":[{"kind":128,"name":"$message","location":[61,32,61,40],"description":"The error message","scope":"__construct","type":"string"},{"kind":128,"name":"$lineno","location":[61,42,61,54],"description":"The template line where the error occurred","scope":"__construct","value":"-1","type":"int"},{"kind":128,"name":"$source","location":[61,56,61,70],"description":"The source context where the error occurred","scope":"__construct","value":"null","type":"Twig_Source|string|null"},{"kind":128,"name":"$previous","location":[61,72,61,98],"description":"The previous exception","scope":"__construct","value":"null","typeSource":1,"type":"Exception"}]},{"kind":32,"name":"getRawMessage","modifiers":1,"location":[97,4,100,5],"description":"Gets the raw message.","scope":"Twig_Error","type":"string"},{"kind":32,"name":"getTemplateFile","modifiers":1,"location":[109,4,114,5],"description":"Gets the logical name where the error occurred.","scope":"Twig_Error","type":"string"},{"kind":32,"name":"setTemplateFile","modifiers":1,"location":[123,4,130,5],"description":"Sets the logical name where the error occurred.","scope":"Twig_Error","children":[{"kind":128,"name":"$name","location":[123,36,123,41],"description":"The name\n","scope":"setTemplateFile","type":"string"}]},{"kind":32,"name":"getTemplateName","modifiers":1,"location":[139,4,144,5],"description":"Gets the logical name where the error occurred.","scope":"Twig_Error","type":"string"},{"kind":32,"name":"setTemplateName","modifiers":1,"location":[153,4,161,5],"description":"Sets the logical name where the error occurred.","scope":"Twig_Error","children":[{"kind":128,"name":"$name","location":[153,36,153,41],"description":"The name\n","scope":"setTemplateName","type":"string"}]},{"kind":32,"name":"getTemplateLine","modifiers":1,"location":[168,4,171,5],"description":"Gets the template line where the error occurred.","scope":"Twig_Error","type":"int"},{"kind":32,"name":"setTemplateLine","modifiers":1,"location":[178,4,183,5],"description":"Sets the template line where the error occurred.","scope":"Twig_Error","children":[{"kind":128,"name":"$lineno","location":[178,36,178,43],"description":"The template line","scope":"setTemplateLine","type":"int"}]},{"kind":32,"name":"getSourceContext","modifiers":1,"location":[190,4,193,5],"description":"Gets the source context of the Twig template where the error occurred.","scope":"Twig_Error","type":"Twig_Source|null"},{"kind":32,"name":"setSourceContext","modifiers":1,"location":[198,4,209,5],"description":"Sets the source context of the Twig template where the error occurred.","scope":"Twig_Error","children":[{"kind":128,"name":"$source","location":[198,37,198,63],"scope":"setSourceContext","value":"null","typeSource":1,"type":"Twig_Source"}]},{"kind":32,"name":"guess","modifiers":1,"location":[211,4,215,5],"scope":"Twig_Error"},{"kind":32,"name":"__call","modifiers":1,"location":[227,4,234,5],"description":"For PHP < 5.3.0, provides access to the getPrevious() method.","scope":"Twig_Error","type":"Exception","children":[{"kind":128,"name":"$method","location":[227,27,227,34],"description":"The method name","scope":"__call","type":"string"},{"kind":128,"name":"$arguments","location":[227,36,227,46],"description":"The parameters to be passed to the method\n","scope":"__call","type":"array"}]},{"kind":32,"name":"appendMessage","modifiers":1,"location":[236,4,240,5],"scope":"Twig_Error","children":[{"kind":128,"name":"$rawMessage","location":[236,34,236,45],"scope":"appendMessage"}]},{"kind":32,"name":"updateRepr","modifiers":2,"location":[245,4,288,5],"scope":"Twig_Error"},{"kind":32,"name":"guessTemplateInfo","modifiers":2,"location":[293,4,363,5],"scope":"Twig_Error"}]}]}}