{"uri":"file:///home/tarcisio/dev/phpfin/vendor/symfony/debug/Exception/FatalThrowableError.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Symfony\\Component\\Debug\\Exception","location":[11,0,11,44]},{"kind":1,"name":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","location":[18,0,43,1],"associated":[{"kind":1,"name":"Symfony\\Component\\Debug\\Exception\\FatalErrorException"}],"description":"Fatal Throwable Error.","children":[{"kind":32,"name":"__construct","modifiers":1,"location":[20,4,42,5],"scope":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","children":[{"kind":128,"name":"$e","location":[20,32,20,45],"scope":"__construct","typeSource":1,"type":"Throwable"}]}]}]}}