{"uri":"file:///home/tarcisio/dev/phpfin/vendor/twig/twig/lib/Twig/Error/Loader.php","root":{"kind":0,"name":"","children":[{"kind":1,"name":"Twig_Error_Loader","location":[24,0,37,1],"associated":[{"kind":1,"name":"Twig_Error"}],"description":"Exception thrown when an error occurs during template loading.\n\nAutomatic template information guessing is always turned off as\nif a template cannot be loaded, there is nothing to guess.\nHowever, when a template is loaded from another one, then, we need\nto find the current context and this is automatically done by\nTwig_Template::displayWithErrorHandling().\n\nThis strategy makes Twig_Environment::resolveTemplate() much faster.","children":[{"kind":32,"name":"__construct","modifiers":1,"location":[26,4,36,5],"scope":"Twig_Error_Loader","children":[{"kind":128,"name":"$message","location":[26,32,26,40],"scope":"__construct"},{"kind":128,"name":"$lineno","location":[26,42,26,54],"scope":"__construct","value":"-1"},{"kind":128,"name":"$source","location":[26,56,26,70],"scope":"__construct","value":"null"},{"kind":128,"name":"$previous","location":[26,72,26,98],"scope":"__construct","value":"null","typeSource":1,"type":"Exception"}]}]}]}}