{"uri":"file:///home/tarcisio/dev/phpfin/vendor/twig/twig/lib/Twig/Error/Runtime.php","root":{"kind":0,"name":"","children":[{"kind":1,"name":"Twig_Error_Runtime","location":[17,0,19,1],"associated":[{"kind":1,"name":"Twig_Error"}],"description":"Exception thrown when an error occurs at runtime."}]}}